# Branch Protection Rules for Solo Developer
# This file defines practical branch protection rules for individual development

# Main branch protection (production) - Solo developer friendly
main:
  required_status_checks:
    strict: true
    contexts:
      - "foundation-build" # Core build job
      - "security-scan"    # Security scan job
  
  required_pull_request_reviews:
    required_approving_review_count: 0  # Geen reviews vereist voor solo developer
    dismiss_stale_reviews: false
    require_code_owner_reviews: false   # Geen code owner vereist
    require_last_push_approval: false
  
  enforce_admins: false  # Admin kan alles omzeilen
  allow_force_pushes: true   # Force push toegestaan voor solo developer
  allow_deletions: true      # Branch deletion toegestaan
  block_creations: false
  required_conversation_resolution: false
  lock_branch: false
  allow_fork_syncing: true

# Develop branch protection (staging) - Solo developer friendly
develop:
  required_status_checks:
    strict: true
    contexts:
      - "foundation-build" # Core build job
  
  required_pull_request_reviews:
    required_approving_review_count: 0  # Geen reviews vereist
    dismiss_stale_reviews: false
    require_code_owner_reviews: false
    require_last_push_approval: false
  
  enforce_admins: false
  allow_force_pushes: true   # Force push toegestaan
  allow_deletions: true      # Branch deletion toegestaan
  block_creations: false
  required_conversation_resolution: false
  lock_branch: false
  allow_fork_syncing: true

# Feature branch protection (development) - Solo developer friendly
feature:
  required_status_checks:
    strict: false      # Niet strict - basis checks volstaan
    contexts:
      - "foundation-build" # Core build job
  
  required_pull_request_reviews:
    required_approving_review_count: 0  # Geen reviews vereist
    dismiss_stale_reviews: false
    require_code_owner_reviews: false
    require_last_push_approval: false
  
  enforce_admins: false
  allow_force_pushes: true   # Force push toegestaan
  allow_deletions: true      # Branch deletion toegestaan
  block_creations: false
  required_conversation_resolution: false
  lock_branch: false
  allow_fork_syncing: true

# Hotfix branch protection (urgent fixes) - Solo developer friendly
hotfix:
  required_status_checks:
    strict: false      # Niet strict voor snelle fixes
    contexts:
      - "foundation-build" # Core build job
  
  required_pull_request_reviews:
    required_approving_review_count: 0  # Geen reviews vereist
    dismiss_stale_reviews: false
    require_code_owner_reviews: false
    require_last_push_approval: false
  
  enforce_admins: false
  allow_force_pushes: true   # Force push toegestaan
  allow_deletions: true      # Branch deletion toegestaan
  block_creations: false
  required_conversation_resolution: false
  lock_branch: false
  allow_fork_syncing: true
