# Branch Protection Rules for Banking-Grade CI/CD
# This file defines the branch protection rules that enforce quality gates

# Main branch protection (production)
main:
  required_status_checks:
    strict: true
    contexts:
      - "Quality Gates (Lint, Types, Tests)"
      - "Security & Compliance"
      - "Build & Validation"
      - "Documentation Compliance"
      - "Pipeline Status & Quality Gate Enforcement"
  
  required_pull_request_reviews:
    required_approving_review_count: 2
    dismiss_stale_reviews: true
    require_code_owner_reviews: true
    require_last_push_approval: true
  
  enforce_admins: true
  allow_force_pushes: false
  allow_deletions: false
  block_creations: false
  required_conversation_resolution: true
  lock_branch: false
  allow_fork_syncing: true

# Develop branch protection (staging)
develop:
  required_status_checks:
    strict: true
    contexts:
      - "Quality Gates (Lint, Types, Tests)"
      - "Security & Compliance"
      - "Build & Validation"
      - "Documentation Compliance"
      - "Pipeline Status & Quality Gate Enforcement"
  
  required_pull_request_reviews:
    required_approving_review_count: 1
    dismiss_stale_reviews: true
    require_code_owner_reviews: false
    require_last_push_approval: true
  
  enforce_admins: false
  allow_force_pushes: false
  allow_deletions: false
  block_creations: false
  required_conversation_resolution: true
  lock_branch: false
  allow_fork_syncing: true

# Feature branch protection (development)
feature:
  required_status_checks:
    strict: true
    contexts:
      - "Quality Gates (Lint, Types, Tests)"
      - "Security & Compliance"
      - "Build & Validation"
  
  required_pull_request_reviews:
    required_approving_review_count: 1
    dismiss_stale_reviews: true
    require_code_owner_reviews: false
    require_last_push_approval: false
  
  enforce_admins: false
  allow_force_pushes: true
  allow_deletions: true
  block_creations: false
  required_conversation_resolution: false
  lock_branch: false
  allow_fork_syncing: true

# Hotfix branch protection (urgent fixes)
hotfix:
  required_status_checks:
    strict: true
    contexts:
      - "Quality Gates (Lint, Types, Tests)"
      - "Security & Compliance"
      - "Build & Validation"
  
  required_pull_request_reviews:
    required_approving_review_count: 2
    dismiss_stale_reviews: true
    require_code_owner_reviews: true
    require_last_push_approval: true
  
  enforce_admins: false
  allow_force_pushes: false
  allow_deletions: false
  block_creations: false
  required_conversation_resolution: true
  lock_branch: false
  allow_fork_syncing: true