# Branch Protection Rules
# This file configures branch protection for the repository

# Main branch protection (production)
main:
  required_status_checks:
    strict: true
    contexts:
      - "🧪 Lint & Test"
      - "🚀 Deploy to Production"
  enforce_admins: true
  required_pull_request_reviews:
    required_approving_review_count: 1
    dismiss_stale_reviews: true
    require_code_owner_reviews: false
  restrictions:
    users: []  # No direct pushes allowed
    teams: []  # No direct pushes allowed
  required_linear_history: true
  allow_force_pushes: false
  allow_deletions: false

# Preview branch protection (staging)
preview:
  required_status_checks:
    strict: true
    contexts:
      - "🧪 Lint & Test"
      - "🚀 Deploy Preview to Staging"
  enforce_admins: false
  required_pull_request_reviews:
    required_approving_review_count: 0
    dismiss_stale_reviews: false
    require_code_owner_reviews: false
  restrictions:
    users: []  # Allow pushes from feature branches
    teams: []
  required_linear_history: false
  allow_force_pushes: false
  allow_deletions: false

# Develop branch protection
develop:
  required_status_checks:
    strict: true
    contexts:
      - "🧪 Lint & Test"
  enforce_admins: false
  required_pull_request_reviews:
    required_approving_review_count: 0
    dismiss_stale_reviews: false
    require_code_owner_reviews: false
  restrictions:
    users: []
    teams: []
  required_linear_history: false
  allow_force_pushes: false
  allow_deletions: false

# Feature branches (allow direct pushes for development)
feature/*:
  required_status_checks:
    strict: false
    contexts:
      - "🧪 Lint & Test"
  enforce_admins: false
  required_pull_request_reviews:
    required_approving_review_count: 0
    dismiss_stale_reviews: false
    require_code_owner_reviews: false
  restrictions:
    users: []
    teams: []
  required_linear_history: false
  allow_force_pushes: true
  allow_deletions: true

# Fix branches (allow direct pushes for hotfixes)
fix/*:
  required_status_checks:
    strict: false
    contexts:
      - "🧪 Lint & Test"
  enforce_admins: false
  required_pull_request_reviews:
    required_approving_review_count: 0
    dismiss_stale_reviews: false
    require_code_owner_reviews: false
  restrictions:
    users: []
    teams: []
  required_linear_history: false
  allow_force_pushes: true
  allow_deletions: true

# Hotfix branches (allow direct pushes for urgent fixes)
hotfix/*:
  required_status_checks:
    strict: false
    contexts:
      - "🧪 Lint & Test"
  enforce_admins: false
  required_pull_request_reviews:
    required_approving_review_count: 0
    dismiss_stale_reviews: false
    require_code_owner_reviews: false
  restrictions:
    users: []
    teams: []
  required_linear_history: false
  allow_force_pushes: true
  allow_deletions: true