# AI Pipeline v2.0 Configuration
# Configure your AI agents, LLM providers, and pipeline behavior

# LLM Provider Configuration
llm:
  provider: "openai"  # openai, claude, copilot (future)
  model: "gpt-4"      # gpt-4, gpt-3.5-turbo, claude-3, etc.
  api_key: "${OPENAI_API_KEY}"  # Environment variable
  max_tokens: 4000
  temperature: 0.1    # Low temperature for consistent code fixes

# Quality Settings
quality:
  threshold: 85       # Minimum quality score (0-100)
  max_iterations: 5   # Maximum improvement cycles
  auto_apply_fixes: true  # Automatically apply fixes
  require_validation: true # Require AI validation before applying

# Agent Configuration
agents:
  issue_collector:
    enabled: true
    description: "Finds code issues and problems"
    focus:
      - security
      - performance  
      - quality
      - typescript
    max_issues_per_file: 50
  
  code_fixer:
    enabled: true
    description: "Generates and applies code fixes"
    focus:
      - security
      - performance
      - quality
      - typescript
    max_fixes_per_iteration: 10
    confidence_threshold: 70  # Only apply fixes with 70%+ confidence
  
  test_generator:
    enabled: true
    description: "Generates test cases for issues"
    focus:
      - unit_tests
      - integration_tests
      - security_tests
    test_framework: "jest"  # jest, mocha, vitest
  
  quality_validator:
    enabled: true
    description: "Validates fixes and assesses quality"
    validation_mode: "ai"  # ai, pattern, hybrid

# Pipeline Behavior
pipeline:
  backup_files: true      # Create backups before applying fixes
  git_integration: false  # Enable Git commits (future)
  output_format: "json"   # json, markdown, html
  verbose_logging: true   # Detailed console output
  
# File Patterns
files:
  include:
    - "**/*.ts"
    - "**/*.js" 
    - "**/*.tsx"
    - "**/*.jsx"
    - "**/*.py"
    - "**/*.java"
    - "**/*.go"
    - "**/*.rs"
  exclude:
    - "**/node_modules/**"
    - "**/dist/**"
    - "**/build/**"
    - "**/*.test.*"
    - "**/*.spec.*"

# Advanced Settings
advanced:
  retry_attempts: 3
  timeout_seconds: 30
  batch_size: 5          # Process files in batches
  parallel_processing: true