feature: "test-feature"
stages:
  spec: pending
  tech: pending
  impl: pending
  test: pending
  sec: pending
  perf: pending
  docs: pending
  ready: pending
current_stage: spec
current_status: in_progress
emergency_stop: false
notes: "Started pipeline for test-feature"
created_at: "2025-09-03"
last_updated: "2025-09-03"