name: Debug Test

on:
  push:
    branches: [ main ]

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Debug Step
        run: |
          echo "Debug workflow is running!"
          echo "Current time: $(date)"
          echo "GitHub SHA: ${{ github.sha }}"