name: "Secret Scan"

on:
  pull_request:
    branches: [ "preview" ]
  push:
    branches: [ "preview" ]
  workflow_dispatch:

jobs:
  secret-scan:
    name: Secret Scan
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Run TruffleHog
      uses: trufflesecurity/trufflehog@main
      with:
        path: ./
        base: ${{ github.event.pull_request.base.sha || 'HEAD~1' }}
        head: ${{ github.event.pull_request.head.sha || 'HEAD' }}
        extra_args: --only-verified --fail

    - name: Run Gitleaks
      uses: gitleaks/gitleaks-action@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        repository-path: ./
        config-path: .gitleaks.toml
        redact: true