name: Test Parallel Execution

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  # Job 1: Build (moet eerst slagen)
  build:
    runs-on: ubuntu-latest
    name: 🔨 Build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build project
        run: npm run build

  # Job 2: Test Job A (parallel met B en C)
  job-a:
    runs-on: ubuntu-latest
    name: 🧪 Job A
    needs: [build] # Wacht op build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Run Job A
        run: |
          echo "🚀 Starting Job A..."
          sleep 10
          echo "✅ Job A completed in 10 seconds"

  # Job 3: Test Job B (parallel met A en C)
  job-b:
    runs-on: ubuntu-latest
    name: 🔍 Job B
    needs: [build] # Wacht op build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Run Job B
        run: |
          echo "🚀 Starting Job B..."
          sleep 15
          echo "✅ Job B completed in 15 seconds"

  # Job 4: Test Job C (parallel met A en B)
  job-c:
    runs-on: ubuntu-latest
    name: 🎯 Job C
    needs: [build] # Wacht op build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Run Job C
        run: |
          echo "🚀 Starting Job C..."
          sleep 20
          echo "✅ Job C completed in 20 seconds"

  # Job 5: Final (wacht op alle parallelle jobs)
  final:
    runs-on: ubuntu-latest
    name: 🎉 Final
    needs: [job-a, job-b, job-c] # Wacht op alle parallelle jobs
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Final Summary
        run: |
          echo "🎉 All parallel jobs completed successfully!"
          echo "📊 Parallel execution summary:"
          echo "   - Job A: ✅ Completed"
          echo "   - Job B: ✅ Completed"
          echo "   - Job C: ✅ Completed"
          echo "🚀 Ready for next steps!"